### ISSUE TITLE
Lightning import fails

### ISSUE THREAD

**Issue by meverson86** [rasbt/scipy2023-deeplearning#2]
Hi there!  Just went to set up my environment for the tutorial and encountered an issue importing lightning.  Turns out that pydantic 2.0.X caused a regression:

```
ImportError: cannot import name 'ModelMetaclass' from 'pydantic.main' (/root/miniconda3/envs/pytorch_tutorial/lib/python3.11/site-packages/pydantic/main.py)
```

When I added `pydantic < 2` to the requiremets.txt file, everything worked fine.

**Comment by EricThomson** [comment]
Same for me: `pip install pydantic==1.10.11 --upgrade` worked for me after installing everything, as discussed here:
https://github.com/Lightning-AI/lightning/issues/18027

But I like `pydantic < 2` more :smile:

**Comment by matthewfeickert** [comment]
As mentioned in https://github.com/Lightning-AI/lightning/issues/18027 and https://github.com/Lightning-AI/lightning/pull/18022, [`lightning` `v2.0.5`](https://pypi.org/project/lightning/2.0.5/) was made about 15 minutes ago which caps `pydantic` to be `<v2.0`. [Hopefully this upper bound is short lived](https://iscinumpy.dev/post/bound-version-constraints/).

**Comment by rasbt** [comment]
Thanks a lot for opening this issue @meverson86! For some reason, I totally missed this notification but fortunately saw it during the workshop. This was super helpful! And luckily this also got fixed as @matthewfeickert mentioned.
